### PR TITLE
Add a CODEOWNERS file

### PR DESCRIPTION
**Pull request by alexef**
Add a CODEOWNERS file based on either the existing _gygservice.yml_ file or the top committers to this repo.
Note that a codeowners file is important to ensure automated PRs are assigned to the correct team.

### CODE REVIEW

**Comment by pvonr** [comment]
This should go to @getyourguide/fintech IMO - FYI @huguenin

**Comment by costash** [comment]
> This should go to @getyourguide/fintech IMO - FYI @huguenin

Is this repo even used anywhere @pvonr ?

**Comment by huguenin** [comment]
+1 @pvonr I think you know this better than us :) Happy to talk. Then again, it probably doesn't need changes anytime soon.

**Comment by pvonr** [comment]
> > This should go to @getyourguide/fintech IMO - FYI @huguenin
> 
> Is this repo even used anywhere @pvonr ? It's the first time I see it 😱

Yes it is @costash  😉

**Pull request merged**
